name: Build OBSCopilot

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest

  build-windows:
    needs: test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean --onefile --windowed --name OBSCopilot --icon=assets/icon.ico obscopilot/main.py
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: OBSCopilot-Windows
        path: dist/OBSCopilot.exe

  build-macos:
    needs: test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean --onefile --windowed --name OBSCopilot --icon=assets/icon.icns obscopilot/main.py
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: OBSCopilot-macOS
        path: dist/OBSCopilot

  build-linux:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean --onefile --name OBSCopilot obscopilot/main.py
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: OBSCopilot-Linux
        path: dist/OBSCopilot

  release:
    needs: [build-windows, build-macos, build-linux]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        name: OBSCopilot-Windows
        path: windows
    - name: Download macOS artifact
      uses: actions/download-artifact@v3
      with:
        name: OBSCopilot-macOS
        path: macos
    - name: Download Linux artifact
      uses: actions/download-artifact@v3
      with:
        name: OBSCopilot-Linux
        path: linux
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          windows/OBSCopilot.exe
          macos/OBSCopilot
          linux/OBSCopilot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 